services:
  - type: web
    name: fd-backend
    runtime: java
    plan: free
    autoDeploy: true

    healthCheckPath: /api/health

    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod

      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: postgresql://fountlinedigital_user:khqiRCYepraQvroMAq9qX7JnizPCIhs8@dpg-d6h5dpvgi27c73fjun10-a/fountlinedigital
          property: connectionString

      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: fountlinedigital_user
          property: user

      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: khqiRCYepraQvroMAq9qX7JnizPCIhs8
          property: password

databases:
  - name: fountlinedigital
    plan: free
    databaseName: fountlinedigital
    user: fountlinedigital_user