server:
  port: 8080

spring:
  application:
    name: fd-backend

  datasource:
    url: jdbc:postgresql://fountlinedigital_user:khqiRCYepraQvroMAq9qX7JnizPCIhs8@dpg-d6h5dpvgi27c73fjun10-a/fountlinedigital
    username: fountlinedigital_user
    password: khqiRCYepraQvroMAq9qX7JnizPCIhs8
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  spring:
    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
app:
  seed:
    enabled: false
    admins: 10
    employees: 200
    clients: 150
    inventory: 200