# Exported from Render on 2026-02-28T02:59:59Z
version: "1"
projects:
- name: fountlinedigital
  environments:
  - name: Production
    databases:
    - name: fountlinedigital
      databaseName: fountlinedigital
      user: fountlinedigital_user
      plan: free
      region: ohio
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
